CREATE TABLE answer
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text        VARCHAR(255),
    question_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_answer PRIMARY KEY (id)
);

CREATE TABLE question
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    question_title VARCHAR(255),
    question_body  VARCHAR(255),
    CONSTRAINT pk_question PRIMARY KEY (id)
);

CREATE TABLE quiz
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT pk_quiz PRIMARY KEY (id)
);

ALTER TABLE answer
    ADD CONSTRAINT FK_ANSWER_ON_QUESTION FOREIGN KEY (question_id) REFERENCES question (id);